---
# This playbook deploys a basic Splunk Enterprise (Core) installation

- name: Apply prereqs to all nodes
  hosts: splunk_server_1 
  gather_facts: no
  roles:
    - prereqs

- name: Install Splunk
  hosts: splunk_server_1
  roles:
    - core-install


